### ISSUE TITLE
Feature Embedding Question

### ISSUE THREAD

**Issue by SvenGroen** [pfnet-research/CSDI_T#1]
Hi,

I am interested in your Embedding Preprocessing of the tabular data and was hoping you can maybe help me out with a few small questions I have:

In your Paper you wrote that you embed the categorical and numerical values of the tabular data into an embedding space.
For recovering the original structure from the newly created embeddings of the model you use the following scheme:
> For numerical variables, we divide the diffusion model output by the corresponding embedding element-wise and use the average value as the final model output. For categorical variables, we calculate the Euclidean distance between CSDI_T outputs and every categorical embedding and set the category of closest embedding (i.e., 1-nearest neighbor) as the final model output. (page 3)

I am thinking about doing something similar and wanted to have a look at your code and see how exactly you are doing this.

Q1: Did I understand it correctly that all the embedding is basically handled by the [Tokenizer](https://github.com/pfnet-research/CSDI_T/blob/d7655578d51b062fefb16656ba635478b458c92d/src/main_model_table_ft.py#L13) class?
Where the forward function creates the embeddings and the recover function reverses the embedding, correct?

Q2: in [the recovery](https://github.com/pfnet-research/CSDI_T/blob/d7655578d51b062fefb16656ba635478b458c92d/src/main_model_table_ft.py#L66) process our batch is of shape [64, 120, 1] (and will be transformed to [64,15,8] which you save as B, L and K. What is the meaning of L and K. My guess is that L = number_of_columns, but what about K?

Q3: Another small question I have is regarding the term "Token" in this scenario. Is a "Token" in this case equivalent to a single tabular cell entry? 

Sorry for the long message 😄 

Best,
Sven

**Comment by joshua-shuhan** [comment]
Hi SvenGroen!

Thanks for your interest and query! I give my thoughts as follows.

To Q1: The short answer is yes. All embedding is handled by the Tokenizer class. For example, the numerical variable is handled by [code here](https://github.com/pfnet-research/CSDI_T/blob/d7655578d51b062fefb16656ba635478b458c92d/src/main_model_table_ft.py#L51), and the categorical variables are handled by Lines 53-59 [here](https://github.com/pfnet-research/CSDI_T/blob/main/src/main_model_table_ft.py#L57) during the forward process.

To Q2: Indeed, `L` = number_of_columns, or, say, the number of features in raw tabular data input. In our implementation, we follow the convention in CSDI, so we keep that `K` dimension. However, since `L` already represents the feature dimension, `K` does not have any special meaning (`K` always equals 1). 

To Q3: I am not sure if I understand the question correctly. However, the original paper gives a good explanation of Tokenization for tabular data (see Fig1 and Fig2 [here](https://arxiv.org/abs/2106.11959v2)). 

Hope this information helps.

Best,
Shuhan

**Comment by SvenGroen** [comment]
Hi Shuhan,

Thanks for the great explanation, you really helped me and I think I understood it now!

Two last question that came up to me that I want to ask to make sure I understood correctly:
(I have never worked with embeddings so far, so sorry if these are stupid questions)

Q4: A vector of shape [64, 15, 8] can be explained like this: "We have a vector with a batch_size of 64 from a tabular data set that has 15 columns/features and each cell entry is embedded into a vector length of 8".
--> Is this interpretation correct?

Q5: We are not learning the embedding, correct? Due to [Line 28](https://github.com/pfnet-research/CSDI_T/blob/d7655578d51b062fefb16656ba635478b458c92d/src/main_model_table_ft.py#L28) and [Line 32](https://github.com/pfnet-research/CSDI_T/blob/d7655578d51b062fefb16656ba635478b458c92d/src/main_model_table_ft.py#L32). We just use the kaiming_uniform initialization for the embedding.

Thank you so much for taking the time to answer my questions!

Best,
Sven

**Comment by joshua-shuhan** [comment]
Hi Sven,

Thanks for your questions.

To Q4: Yes, exactly!

To Q5: Yes, both numerical and categorical embeddings are not trainable in our implementation.

I hope my answer helps.

Best,
Shuhan

**Comment by SvenGroen** [comment]
Thank you very much for all the answers!
